language: python
python:
  - 2.6
  - 2.7
  - 3.1
  - 3.2
env:
  - TIMEZONE=UTC
install:
  - pip install nose
  - pip install coverage
  - pip install mock
  - pip install .
script: nosetests -s tests
